server:
  port: 80

spring:
  application:
    name: '@project.name@'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
  register-with-eureka: true #false表示自己不向注册中心注册自己
  fetch-registry: true  #fasle表示自己是注册中心 职责是维护服务实例 不需要去检索服务
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true


zuul:
  ignored-services: '*'
  prefix: /springcloud #对外接口加上同统一的前缀
  routes:
    #consum:  #路由名称 随便写
     # path: /client/** #服务的路径的映射名字
      #service-id: consum #被访问的应用
   # product:  #路由名称 随便写
     # path: /server/** #服务的路径的映射名字
      #service-id: product #被访问的应用
    product: /server/**
    consum: /client/**

