server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/  #注册中心集群 填写其他中心的服务地址 单节点填写自己的地址
    register-with-eureka: false #表示自己不向注册中心注册自己
    fetch-registry: false  #表示自己是注册中心 职责是维护服务实例 不需要去检索服务

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #在管理界面展示IP地址
    prefer-ip-address: true  #在管理界面展示IP地址
spring:
  application:
    name: '@project.name@'
