server:
  port: 9001

spring:
  application:
    name: '@project.name@'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8001:8001/eurek a/,http://eureka8002:8002/eureka/
  register-with-eureka: true #false表示自己不向注册中心注册自己
  fetch-registry: true  #fasle表示自己是注册中心 职责是维护服务实例 不需要去检索服务
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true


zuul:
  prefix: /mytest #对外接口加上同统一的前缀
  routes:
    consum:  #路由名称 随便写
      path: /api/** #服务的路径的映射名字
      service-id: consum80 #被访问的应用
  ignored-services: '*'
